# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: pytest
    - name: Generate coverage
      run:  pytest --cov=./ --cov-report=xml
    - name: "Upload coverage to Codecov"
      uses: codecov/codecov-action@v2
      with:
        fail_ci_if_error: true
    - name: Generate documentation
      run: |
        cd ${{ github.workspace }}/docs ; \
        find . -name "*.html" -type f -delete ; \
        cd ${{ github.workspace }}/src ; \
        pdoc3 --html . -o ${{ github.workspace }}/docs --force --template-dir ${{ github.workspace }}/docs ; \
        mv ${{ github.workspace }}/docs/src/* ${{ github.workspace }}/docs/
    - name: Commit to repo
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add ./docs/*
        if ! git diff-index --quiet HEAD; then
           git commit -m "Update documentation and coverage badge."
           git fetch origin main
           git push origin HEAD:main
        fi
